### ISSUE TITLE
Как запустить проект без TypeScript? (Run project without TypeScript)

### ISSUE THREAD

**Issue by tsvetkovpro** [yegor-sytnyk/contoso-express#5]
можно ли запустить проект без TypeScript?

**Comment by yegor-sytnyk** [comment]
я планирую добавить ALT ветку c JS имплементацией, пока что надо хотябы один раз скомпилировать в JS, при этом сам JS код будет читабельным, но не идеальным (напрмер некоторые переменные будут с суфиксом _1)

**Comment by tsvetkovpro** [comment]
что я могу сделать чтобы помочь вам разработкой альтернативной ветки?

**Comment by yegor-sytnyk** [comment]
я планирую заняться этим на следующей неделе, то с чем надо разобраться - как использовать async/await в JS с Babel, если вас устраивает использование промисов, то проблем с конвертацией быть не должно, могу помочь если будут какие-то сложности, я написал новую статью на хабре, там подробнее о TS и как без него обойтись

**Comment by tsvetkovpro** [comment]
простите ,  не хватает квалификации понять как иcпользовать ваш проект без ts. Я прочитал : 

Если вы не хотите использовать TS, то вы легко можете преобразовать TS код в JS. Основное, что надо сделать:

преобразовать ES6 imports в Node require
убрать аннотации типов
использовать промисы вместо asyn/await или подключить babel для транспиляции

но как это сделать  не пойму, могу я подождать пока вы включите возможность работы без тайпскрипта?

**Comment by yegor-sytnyk** [comment]
сконвертировал TS-JS, ветка js-react

там не хватает линтера JSLint

плюс надо разобраться с warnings в консоли, но так вроде все работает

для запуска компиляции клиента
webpack

для запуска компиляции сервера
webpack --config webpack.config.server.js

файл для запуска сервера /build/server/serverBundle.js

**Comment by yegor-sytnyk** [comment]
Done. Branch Alt/JS
